import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import FirstNav from "./_components/FirstNav/FirstNav";
import { Toaster } from "@/components/ui/toast";
import MySessionProvider from "./_components/MySessionProvider/MySessionProvider";
import Providers from "./_components/TanStackProvider/TanStackProvider";

const ExoFont = Exo({
  variable: "--font-exo",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${ExoFont.className} antialiased`}>
      <body>
          <Providers>
            <MySessionProvider>
              <FirstNav />
              <Navbar />
              {children}
              <Toaster />
              <Footer />
            </MySessionProvider>
          </Providers>
      </body>
    </html>
  );
}
